version: '3.7'

services:
  redis:
    image: redis:4.0.14-alpine
    ports:
      - '6379:6379'
    expose:
      - '6379'

    environment:
     - REDIS_HOST=redis
     - NODE_ENV=development
     - PORT=3000
     - REDIS_PORT=6379
